trigger:
- main

pr:
- main

jobs:
- template: azure-windows.yml
  parameters:
    name: windows_debug_x86
    pool: windows-latest
    configuration: Debug
    architecture: x86
    testwin32metadata: false

- template: azure-windows.yml
  parameters:
    name: windows_release_x86
    pool: windows-latest
    configuration: Release
    architecture: x86
    testwin32metadata: false

- template: azure-windows.yml
  parameters:
    name: windows_debug_x64
    pool: windows-latest
    configuration: Debug
    architecture: x64
    testwin32metadata: false

- template: azure-windows.yml
  parameters:
    name: windows_release_x64
    pool: windows-latest
    configuration: Release
    architecture: x64
    testwin32metadata: false

- template: azure-windows.yml
  parameters:
    name: test_win32metadata
    pool: windows-latest
    configuration: Release
    architecture: x64
    testwin32metadata: true

- template: azure-windows.yml
  parameters:
    name: build_nuget
    pool: windows-latest
    configuration: Release
    architecture: x64
    testwin32metadata: false
    EXCLUDE_BUILDNUMBER_FROM_PACKAGE: true

- template: azure-unix.yml
  parameters:
    name: ubuntu_debug_x64
    pool: ubuntu-latest
    configuration: Debug
    architecture: x64
    OVERRIDE_RUNTIME_IDENTIFIER: ubuntu.18.04-x64

- template: azure-unix.yml
  parameters:
    name: ubuntu_release_x64
    pool: ubuntu-latest
    configuration: Release
    architecture: x64
    OVERRIDE_RUNTIME_IDENTIFIER: ubuntu.18.04-x64
